# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

language: en
tone_instructions:
    "Be concise, engineering-focused, and avoid creative writing."
early_access: false

chat:
    auto_reply: true

reviews:
    collapse_walkthrough: true

    auto_review:
        enabled: true
        drafts: false
        ignore_title_keywords:
            - WIP
            - DRAFT
            - DO NOT MERGE
            - NO REVIEW

    commit_status: false
